### PR TITLE
0218 threshold naming bug

### LINKED ISSUE #218: Keys can be dropped into the threshold row
### Description

Keys can be dragged to the threshold row. The app should now allow you to do this for a row that was for the threshold value
Screen Shot 2022-01-26 at 8 21 13 PM
.

### Steps to reproduce

see above

### Additional context

_No response_

### Hedera network

other

### Version

0.7.0

### Operating system

_No response_

### LINKED ISSUE #219: Update error message for invalid thresholds
### Description

Not sure if the "-" is supposed to be there in the pop-up
Screen Shot 2022-01-26 at 8 23 20 PM

### Steps to reproduce

see above

### Additional context

_No response_

### Hedera network

other

### Version

0.7.0

### Operating system

_No response_

### LINKED ISSUE #220: Cannot set a nested threshold key value
### Description

The third level threshold cannot be set. If you double click on it nothing pops up. If the threshold value cannot be set there should be an error message that is displayed to the user.

Screen Shot 2022-01-26 at 8 26 13 PM

### Steps to reproduce

see above

### Additional context

_No response_

### Hedera network

other

### Version

0.7.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by DSMatusevich**
**Description**:
- Changing naming scheme for thresholds (#218)
- Added a popup when a threshold cannot be set (#220 )
- Updated the missing threshold error message (#219)

**Related issue(s)**:

Closes #218 
Closes #219 
Closes #220 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: tools-ui/src/main/java/com/hedera/hashgraph/client/ui/popups/KeyDesignerPopup.java [hunk 1]
```diff
@@ -118,6 +118,8 @@
 	public static final String REMOVE_BUTTON_STYLE =
 			"-fx-background-color: transparent; -fx-text-fill: red;-fx-border-color: indianred; " +
 					"-fx-border-radius: 5";
+	public static final String CANNOT_UPDATE_THRESHOLD =
+			"The selected threshold does not have a list of keys associated with it. The threshold cannot be updated";
```
Comment (qnswirlds) [inline tools-ui/src/main/java/com/hedera/hashgraph/client/ui/popups/KeyDesignerPopup.java:122]: As this field is not shared to any other class, it should be `private`. If it has to be shared, consider package scope before making it `public`. The same guideline applies to fields above this one that you did not touch.

Comment (DSMatusevich) [reply tools-ui/src/main/java/com/hedera/hashgraph/client/ui/popups/KeyDesignerPopup.java:122]: makes sense. I will make the change
