### PR TITLE
0020 exclude macos from volumes list

### LINKED ISSUE #20: Application fails to start
### Description

On a fresh install of the app, the application only shows the home pane, with no transactions.

### Steps to reproduce

1. Install v0.1.0
2. run the app
[logs.zip](https://github.com/hashgraph/hedera-transaction-tool-demo/files/6924647/logs.zip)

### Additional context

_No response_

### Hedera network

other

### Version

v0.1.0

### Operating system

macOS

### PR DESCRIPTION
**Pull request by DSMatusevich**
**Description**:
Since there is no straightforward way to find usb drives, the application scans all volumes and discards all volumes associated with the native OS. In some laptops that have been rebuilt, the denomination for the HD is different, and this caused the application to crash.

Fixes #20 

**Notes for reviewer**:
Logs in the issue
Also addressed an issue where the verification public key was not appropriately copied to the Files directory

**Checklist**

- [x] Documented (Code comments, README, etc.)

### CODE REVIEW

File: tools-core/src/main/java/com/hedera/hashgraph/client/core/fileservices/FileAdapterFactory.java [hunk 1]
```diff
@@ -16,23 +16,6 @@
...
- * with Swirlds.
- *
- * SWIRLDS MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
- * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
- * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
- * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SWIRLDS SHALL NOT BE LIABLE FOR
- * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
- * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
- */
-
```
Comment (ljianghedera) [inline tools-core/src/main/java/com/hedera/hashgraph/client/core/fileservices/FileAdapterFactory.java:35]: Is there any reason to remove the license header?

Comment (DSMatusevich) [reply tools-core/src/main/java/com/hedera/hashgraph/client/core/fileservices/FileAdapterFactory.java:35]: Yes, this is the wrong license: Originally the tools were part of the Swirlds repo and had a Swirlds license. Now they are part of the Hedera repo. 

For some reason Intellij did not remove all the old licenses when I did the change, but just appended them. I have removed 99% of the wrong files, but if I see one that wasn't removed, I do it manually.

**Review by ljianghedera — APPROVED** [review]
LGTM except the question.
